# Generated by Django 5.2.2 on 2025-06-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('cajaid', models.AutoField(db_column='cajaId', primary_key=True, serialize=False)),
                ('fechaapertura', models.DateTimeField(blank=True, db_column='fechaApertura', null=True)),
                ('fechaciere', models.TextField(blank=True, db_column='fechaCiere', null=True)),
                ('cordobasinicial', models.FloatField(db_column='cordobasInicial')),
                ('dolaresinicial', models.FloatField(db_column='dolaresInicial')),
                ('cordobasfinal', models.FloatField(blank=True, db_column='cordobasFinal', null=True)),
                ('dolaresfinal', models.FloatField(blank=True, db_column='dolaresFinal', null=True)),
                ('totalingresos', models.FloatField(blank=True, db_column='totalIngresos', null=True)),
                ('sobrante', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaid', models.AutoField(db_column='categoriaId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriaropa',
            fields=[
                ('categoriaropaid', models.AutoField(db_column='categoriaRopaId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriaRopa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallefacturas',
            fields=[
                ('detallefacturaid', models.AutoField(db_column='detalleFacturaId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleFacturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallefacturasropa',
            fields=[
                ('detallefacturaropaid', models.AutoField(db_column='detalleFacturaRopaId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleFacturasRopa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('facturaid', models.AutoField(db_column='facturaId', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('cliente', models.TextField(blank=True, null=True)),
                ('cordobas', models.FloatField(blank=True, null=True)),
                ('dolares', models.FloatField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('tasacambio', models.FloatField(blank=True, db_column='tasaCambio', null=True)),
                ('cajaid', models.TextField(blank=True, db_column='cajaId', null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('loteid', models.AutoField(db_column='loteId', primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechavencimiento', models.TextField(db_column='fechaVencimiento')),
                ('preciocompraunitario', models.FloatField(blank=True, db_column='precioCompraUnitario', null=True)),
                ('preciocompralote', models.FloatField(blank=True, db_column='precioCompraLote', null=True)),
                ('cantidad', models.IntegerField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presentaciones',
            fields=[
                ('presentacionid', models.AutoField(db_column='presentacionId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presentaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productoid', models.AutoField(db_column='productoId', primary_key=True, serialize=False)),
                ('codigobarra', models.TextField(blank=True, db_column='codigoBarra', null=True, unique=True)),
                ('rutafoto', models.TextField(blank=True, db_column='rutaFoto', null=True)),
                ('nombre', models.TextField()),
                ('concentracion', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('preciounidad', models.FloatField(db_column='precioUnidad')),
                ('stock', models.IntegerField()),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productosropa',
            fields=[
                ('productoropaid', models.AutoField(db_column='productoRopaId', primary_key=True, serialize=False)),
                ('codigobarraropa', models.TextField(blank=True, db_column='codigoBarraRopa', null=True, unique=True)),
                ('rutafoto', models.TextField(blank=True, db_column='rutaFoto', null=True)),
                ('nombre', models.TextField()),
                ('talla', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productosRopa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('proveedorid', models.AutoField(db_column='proveedorId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rolid', models.AutoField(db_column='rolId', primary_key=True, serialize=False)),
                ('nombrerol', models.TextField(db_column='nombreRol')),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadmedidas',
            fields=[
                ('unidadmedidaid', models.AutoField(db_column='unidadMedidaId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidadMedidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(db_column='usuarioId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('usuario', models.TextField(unique=True)),
                ('contrasena', models.TextField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
