# Generated by Django 5.2.2 on 2025-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriasproducto',
            fields=[
                ('categoriaid', models.AutoField(db_column='categoriaId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'categoriasProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentastemporales',
            fields=[
                ('cuentatemporalid', models.AutoField(db_column='cuentaTemporalId', primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentasTemporales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecuentatemporalplato',
            fields=[
                ('detalleid', models.AutoField(db_column='detalleId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalleCuentaTemporalPlato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecuentatemporalproducto',
            fields=[
                ('detalleid', models.AutoField(db_column='detalleId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalleCuentaTemporalProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallefacturaplato',
            fields=[
                ('detalleid', models.AutoField(db_column='detalleId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.FloatField(db_column='precioUnitario')),
            ],
            options={
                'db_table': 'detalleFacturaPlato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallefacturaproducto',
            fields=[
                ('detalleid', models.AutoField(db_column='detalleId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.FloatField(db_column='precioUnitario')),
            ],
            options={
                'db_table': 'detalleFacturaProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialventas',
            fields=[
                ('historialventaid', models.AutoField(db_column='historialVentaId', primary_key=True, serialize=False)),
                ('cantidadtotal', models.IntegerField(db_column='cantidadTotal')),
                ('fechaventa', models.DateField(db_column='fechaVenta')),
            ],
            options={
                'db_table': 'historialVentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lotesproductos',
            fields=[
                ('loteid', models.AutoField(db_column='loteId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('fechavencimiento', models.DateField(blank=True, db_column='fechaVencimiento')),
                ('preciocompraunitario', models.FloatField(blank=True, db_column='precioCompraUnitario', null=True)),
                ('precioventa', models.FloatField(blank=True, db_column='precioVenta', null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, db_column='stock', null=True)),
            ],
            options={
                'db_table': 'lotesProductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('mesaid', models.AutoField(db_column='mesaId', primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('platoid', models.AutoField(db_column='platoId', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'platos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cajas',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Categoriaropa',
        ),
        migrations.DeleteModel(
            name='Detallefacturas',
        ),
        migrations.DeleteModel(
            name='Detallefacturasropa',
        ),
        migrations.DeleteModel(
            name='Lotes',
        ),
        migrations.DeleteModel(
            name='Presentaciones',
        ),
        migrations.DeleteModel(
            name='Productosropa',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Unidadmedidas',
        ),
    ]
