# Generated by Django 5.2.2 on 2025-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_categoriasproducto_cuentastemporales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('cajaid', models.AutoField(db_column='cajaId', primary_key=True, serialize=False)),
                ('fechaapertura', models.DateTimeField(blank=True, db_column='fechaApertura', null=True)),
                ('fechaciere', models.DateTimeField(blank=True, db_column='fechaCiere', null=True)),
                ('cordobasinicial', models.FloatField(db_column='cordobasInicial')),
                ('dolaresinicial', models.FloatField(db_column='dolaresInicial')),
                ('cordobasfinal', models.FloatField(blank=True, db_column='cordobasFinal', null=True)),
                ('dolaresfinal', models.FloatField(blank=True, db_column='dolaresFinal', null=True)),
                ('totalingresos', models.FloatField(blank=True, db_column='totalIngresos', null=True)),
                ('sobrante', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('faltante', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cocinas',
            fields=[
                ('cocinaid', models.AutoField(db_column='cocinaId', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('horapreparacion', models.TextField(blank=True, db_column='horaPreparacion', null=True)),
                ('horafinalizada', models.TextField(blank=True, db_column='horaFinalizada', null=True)),
                ('estado', models.IntegerField()),
                ('cliente', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cocinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Denominacionescaja',
            fields=[
                ('denominacioncajaid', models.AutoField(db_column='denominacionCajaId', primary_key=True, serialize=False)),
                ('tipodenominacion', models.IntegerField(db_column='tipoDenominacion')),
                ('denominacion', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('tipomovimiento', models.IntegerField(db_column='tipoMovimiento')),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'denominacionescaja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('opcionid', models.AutoField(db_column='opcionId', primary_key=True, serialize=False)),
                ('tasacambio', models.FloatField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('numeroruc', models.TextField(blank=True, db_column='numeroRUC', null=True)),
                ('nombreimpresora', models.TextField(blank=True, db_column='nombreImpresora', null=True)),
            ],
            options={
                'db_table': 'opciones',
                'managed': False,
            },
        ),
    ]
